# Generated by Django 4.2.1 on 2023-06-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='watched_validators',
            field=models.CharField(default='', max_length=4200),
        ),
    ]
