# Generated by Django 4.2.1 on 2023-07-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_watched_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='allowed_validator_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='watched_validators',
            field=models.CharField(default='', max_length=100000),
        ),
    ]
