# Generated by Django 4.1.9 on 2023-05-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField(unique=True)),
                ('slot_number', models.PositiveIntegerField(unique=True)),
                ('block_hash', models.CharField(max_length=64, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('parent_hash', models.CharField(max_length=64)),
                ('validator_count', models.PositiveIntegerField()),
                ('slot', models.PositiveIntegerField()),
                ('epoch', models.PositiveIntegerField()),
                ('participation_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('balance_churn', models.DecimalField(decimal_places=9, max_digits=20)),
                ('attestation_count', models.PositiveIntegerField()),
                ('proposer_slashing_count', models.PositiveIntegerField()),
                ('attester_slashing_count', models.PositiveIntegerField()),
                ('deposit_count', models.PositiveIntegerField()),
                ('voluntary_exit_count', models.PositiveIntegerField()),
                ('block_transfer_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_back', models.IntegerField(default=0)),
                ('last_front', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('validator_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('public_key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('withdrawal_credentials', models.CharField(max_length=128)),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('effective_balance', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('status', models.CharField(choices=[('pending_initialized', 'Pending Initialized'), ('pending_queued', 'Pending Queued'), ('active_ongoing', 'Active Ongoing'), ('active_exiting', 'Active Exiting'), ('active_slashed', 'Active Slashed'), ('exited_unslashed', 'Exited Unslashed'), ('exited_slashed', 'Exited Slashed'), ('withdrawal_possible', 'Withdrawal Possible'), ('withdrawal_done', 'Withdrawal Done'), ('active', 'Active'), ('pending', 'Pending'), ('exited', 'Exited'), ('withdrawal', 'Withdrawal'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=19)),
                ('performance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slashed', models.BooleanField(default=False)),
                ('activation_epoch', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('activation_eligibility_epoch', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('exit_epoch', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
                ('withdrawable_epoch', models.DecimalField(decimal_places=0, default=0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.PositiveIntegerField()),
                ('optimal_inclusion_distance', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('block_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations_included', to='blockfetcher.block')),
                ('block_attesting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='blockfetcher.block')),
            ],
        ),
    ]
