# Generated by Django 4.1.9 on 2023-05-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0004_alter_block_attestation_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='fee_recipient',
            field=models.CharField(max_length=66),
        ),
    ]
