# Generated by Django 4.1.9 on 2023-05-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0005_alter_block_fee_recipient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='parent_hash',
            field=models.CharField(max_length=84),
        ),
    ]
