# Generated by Django 4.1.9 on 2023-05-20 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0006_alter_block_parent_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_hash',
            field=models.CharField(blank=True, max_length=66, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_number',
            field=models.PositiveIntegerField(blank=True, unique=True),
        ),
    ]
