# Generated by Django 4.1.9 on 2023-05-20 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0007_alter_block_block_hash_alter_block_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='block_hash',
            field=models.CharField(blank=True, max_length=66, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='block_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
