# Generated by Django 4.1.9 on 2023-05-21 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0008_alter_block_block_hash_alter_block_block_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='proposer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blockfetcher.block'),
        ),
    ]
