# Generated by Django 4.1.9 on 2023-05-21 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0010_rename_proposer_withdrawal_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='burnt_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
        migrations.AddField(
            model_name='validator',
            name='total_reward',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
        migrations.AddField(
            model_name='validator',
            name='total_tx_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
        migrations.AddField(
            model_name='validator',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
