# Generated by Django 4.1.9 on 2023-05-21 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0011_validator_burnt_fee_validator_total_reward_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validator',
            name='burnt_fee',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='total_reward',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='total_tx_fee',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='transaction_count',
        ),
        migrations.AddField(
            model_name='block',
            name='burnt_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
        migrations.AddField(
            model_name='block',
            name='total_reward',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
        migrations.AddField(
            model_name='block',
            name='total_tx_fee',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
        migrations.AddField(
            model_name='block',
            name='transaction_count',
            field=models.IntegerField(default=0),
        ),
    ]
