# Generated by Django 4.1.9 on 2023-05-21 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0012_remove_validator_burnt_fee_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttestationCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockfetcher.block')),
                ('validators', models.ManyToManyField(to='blockfetcher.validator')),
            ],
        ),
    ]
