# Generated by Django 4.1.9 on 2023-05-21 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0014_alter_attestationcommittee_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockfetcher.block'),
        ),
    ]
