# Generated by Django 4.1.9 on 2023-05-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0015_alter_attestationcommittee_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='slot',
            field=models.IntegerField(),
        ),
    ]
