# Generated by Django 4.1.9 on 2023-05-21 20:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0018_remove_attestationcommittee_validators_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attestationcommittee',
            name='distance',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], size=None),
            preserve_default=False,
        ),
    ]
