# Generated by Django 4.1.9 on 2023-05-22 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0019_attestationcommittee_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='epoch',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='slot_number',
            field=models.PositiveIntegerField(db_index=True, unique=True),
        ),
    ]
