# Generated by Django 4.1.9 on 2023-05-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0021_epoch_proposerduty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='proposer',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
