# Generated by Django 4.1.9 on 2023-05-22 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0022_alter_block_proposer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='proposer',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='validator',
            field=models.IntegerField(db_index=True),
        ),
    ]
