# Generated by Django 4.1.9 on 2023-05-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0023_alter_block_proposer_alter_withdrawal_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='index',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='attestationcommittee',
            name='slot',
            field=models.IntegerField(db_index=True),
        ),
    ]
