# Generated by Django 4.1.9 on 2023-05-23 13:33

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0024_alter_attestationcommittee_index_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attestationcommittee',
            index=django.contrib.postgres.indexes.GinIndex(fields=['validator_ids'], name='blockfetche_validat_70f015_gin'),
        ),
    ]
