# Generated by Django 4.1.9 on 2023-05-23 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0026_alter_attestationcommittee_epoch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='status',
            field=models.CharField(choices=[('pending_initialized', 'Pending Initialized'), ('pending_queued', 'Pending Queued'), ('active_ongoing', 'Active Ongoing'), ('active_exiting', 'Active Exiting'), ('active_slashed', 'Active Slashed'), ('exited_unslashed', 'Exited Unslashed'), ('exited_slashed', 'Exited Slashed'), ('withdrawal_possible', 'Withdrawal Possible'), ('withdrawal_done', 'Withdrawal Done'), ('active', 'Active'), ('pending', 'Pending'), ('exited', 'Exited'), ('withdrawal', 'Withdrawal'), ('unknown', 'Unknown')], default='unknown', max_length=19),
        ),
    ]
