# Generated by Django 4.1.9 on 2023-05-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0027_alter_validator_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='public_key',
            field=models.CharField(db_index=True, max_length=98, unique=True),
        ),
        migrations.AlterField(
            model_name='validator',
            name='withdrawal_credentials',
            field=models.CharField(max_length=66),
        ),
    ]
