# Generated by Django 4.1.9 on 2023-05-24 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0028_alter_validator_public_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='main',
            old_name='last_back',
            new_name='last_checked_epoch',
        ),
        migrations.RenameField(
            model_name='main',
            old_name='last_front',
            new_name='last_slot',
        ),
    ]
