# Generated by Django 4.1.9 on 2023-05-24 14:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0029_rename_last_back_main_last_checked_epoch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='last_balance_snapshot_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ValidatorBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_id', models.PositiveIntegerField()),
                ('balance', models.FloatField()),
                ('date', models.DateField()),
            ],
            options={
                'unique_together': {('validator_id', 'date')},
                'index_together': {('validator_id', 'date')},
            },
        ),
    ]
