# Generated by Django 4.1.9 on 2023-05-24 17:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0030_main_last_balance_snapshot_date_validatorbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='last_balance_snapshot_planned_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
