# Generated by Django 4.2.1 on 2023-05-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0031_main_last_balance_snapshot_planned_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='proposer',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
