# Generated by Django 4.2.1 on 2023-05-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0032_alter_block_proposer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validatorbalance',
            name='balance',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
    ]
