# Generated by Django 4.2.1 on 2023-05-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0033_alter_validatorbalance_balance'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='attestationcommittee',
            name='blockfetche_validat_70f015_gin',
        ),
    ]
