# Generated by Django 4.2.1 on 2023-05-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0035_remove_block_id_alter_attestationcommittee_slot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='slot',
            field=models.IntegerField(db_index=True),
        ),
    ]
