# Generated by Django 4.2.1 on 2023-05-27 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0036_alter_attestationcommittee_slot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='epoch',
            field=models.IntegerField(),
        ),
    ]
