# Generated by Django 4.2.1 on 2023-05-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0037_alter_attestationcommittee_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorbalance',
            name='slot',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
