# Generated by Django 4.2.1 on 2023-05-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0038_validatorbalance_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorbalance',
            name='total_reward',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
    ]
