# Generated by Django 4.2.1 on 2023-05-29 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0040_alter_block_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validatorbalance',
            old_name='total_reward',
            new_name='total_consensus_balance',
        ),
        migrations.AddField(
            model_name='validatorbalance',
            name='execution_reward',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
    ]
