# Generated by Django 4.2.1 on 2023-05-30 14:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0041_rename_total_reward_validatorbalance_total_consensus_balance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpochAttestationReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('epoch', models.PositiveIntegerField(db_index=True)),
                ('head', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('target', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('source', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
            ],
        ),
        migrations.CreateModel(
            name='EpochSyncReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_id', models.PositiveIntegerField(db_index=True)),
                ('epoch', models.PositiveIntegerField(db_index=True)),
                ('reward', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('penalty', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
            ],
        ),
        migrations.AddField(
            model_name='main',
            name='finalized_checkpoint_epoch',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='finalized_checkpoint_root',
            field=models.CharField(default='', max_length=68),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='genesis_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='main',
            name='justified_checkpoint_epoch',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='main',
            name='justified_checkpoint_root',
            field=models.CharField(default='', max_length=68),
            preserve_default=False,
        ),
    ]
