# Generated by Django 4.2.1 on 2023-05-30 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0042_epochattestationreward_epochsyncreward_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='epochattestationreward',
            unique_together={('epoch', 'head', 'target', 'source')},
        ),
    ]
