# Generated by Django 4.2.1 on 2023-05-30 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0043_alter_epochattestationreward_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='epochsyncreward',
            unique_together={('epoch', 'validator_id')},
        ),
    ]
