# Generated by Django 4.2.1 on 2023-05-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0044_alter_epochsyncreward_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpochBlockReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_id', models.PositiveIntegerField(db_index=True)),
                ('epoch', models.PositiveIntegerField(db_index=True)),
                ('attestations', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('sync_aggregate', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('proposer_slashings', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('attester_slashings', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
            ],
            options={
                'unique_together': {('epoch', 'validator_id')},
            },
        ),
    ]
