# Generated by Django 4.2.1 on 2023-05-30 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0045_epochblockreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotBlockReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validator_id', models.PositiveIntegerField(db_index=True)),
                ('epoch', models.PositiveIntegerField(db_index=True)),
                ('attestations', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('sync_aggregate', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('proposer_slashings', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('attester_slashings', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockfetcher.block', unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EpochBlockReward',
        ),
    ]
