# Generated by Django 4.2.1 on 2023-05-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0046_slotblockreward_delete_epochblockreward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epochattestationreward',
            name='epoch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockfetcher.epoch'),
        ),
        migrations.AlterField(
            model_name='epochsyncreward',
            name='epoch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockfetcher.epoch'),
        ),
        migrations.AlterField(
            model_name='slotblockreward',
            name='epoch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blockfetcher.epoch'),
        ),
    ]
