# Generated by Django 4.2.1 on 2023-05-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0048_alter_slotblockreward_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epochattestationreward',
            name='epoch',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='epochsyncreward',
            name='epoch',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='epochsyncreward',
            name='validator_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='slotblockreward',
            name='epoch',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name='slotblockreward',
            unique_together={('epoch', 'validator_id')},
        ),
        migrations.AlterIndexTogether(
            name='epochattestationreward',
            index_together={('epoch', 'validator_ids')},
        ),
        migrations.AlterIndexTogether(
            name='epochsyncreward',
            index_together={('epoch', 'validator_id')},
        ),
        migrations.AlterIndexTogether(
            name='slotblockreward',
            index_together={('epoch', 'validator_id')},
        ),
    ]
