# Generated by Django 4.2.1 on 2023-05-30 19:14

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0051_alter_slotblockreward_unique_together'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='epochattestationreward',
            index=django.contrib.postgres.indexes.GinIndex(fields=['validator_ids'], name='blockfetche_validat_07527b_gin'),
        ),
    ]
