# Generated by Django 4.2.1 on 2023-05-31 21:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0052_epochattestationreward_blockfetche_validat_07527b_gin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='epochattestationreward',
            name='blockfetche_validat_07527b_gin',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='effective_balance',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='performance',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='slashed',
        ),
        migrations.RemoveField(
            model_name='validator',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='attestationcommittee',
            name='missed_attestation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AddField(
            model_name='validator',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
