# Generated by Django 4.2.1 on 2023-06-02 13:34

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0053_remove_epochattestationreward_blockfetche_validat_07527b_gin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='sync_aggregation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='block',
            name='sync_missed',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None),
        ),
        migrations.CreateModel(
            name='SyncCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField(db_index=True, unique=True)),
                ('validator_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
                ('missed', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, null=True, size=None)),
            ],
            options={
                'indexes': [django.contrib.postgres.indexes.GinIndex(fields=['validator_ids'], name='blockfetche_validat_46bf90_gin')],
            },
        ),
    ]
