# Generated by Django 4.2.1 on 2023-06-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0054_block_sync_aggregation_block_sync_missed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='last_missed_attestation_aggregation_epoch',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='attestationcommittee',
            unique_together={('slot', 'index')},
        ),
        migrations.CreateModel(
            name='MissedAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField(db_index=True)),
                ('index', models.IntegerField()),
                ('epoch', models.IntegerField()),
                ('validator_id', models.PositiveIntegerField(db_index=True)),
            ],
            options={
                'unique_together': {('slot', 'index', 'validator_id')},
                'index_together': {('validator_id', 'slot')},
            },
        ),
    ]
