# Generated by Django 4.2.1 on 2023-06-03 22:59

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0056_remove_block_attester_slashing_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='missed_attestation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, db_index=True, default=None, null=True, size=None),
        ),
    ]
