# Generated by Django 4.2.1 on 2023-06-03 23:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0057_alter_attestationcommittee_missed_attestation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='missed_attestation',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=None, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='attestationcommittee',
            name='validator_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), db_index=True, size=None),
        ),
    ]
