# Generated by Django 4.2.1 on 2023-06-03 23:53

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0058_alter_attestationcommittee_missed_attestation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='validator_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(db_index=True), size=None),
        ),
    ]
