# Generated by Django 4.2.1 on 2023-06-03 23:54

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0059_alter_attestationcommittee_validator_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attestationcommittee',
            name='validator_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None),
        ),
    ]
