# Generated by Django 4.2.1 on 2023-06-04 22:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0060_alter_attestationcommittee_validator_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='fee_reward',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
        migrations.AddField(
            model_name='block',
            name='mev_boost_relay',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=25), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='block',
            name='mev_reward',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
        migrations.AddField(
            model_name='block',
            name='mev_reward_recipient',
            field=models.CharField(default='', max_length=66),
            preserve_default=False,
        ),
    ]
