# Generated by Django 4.2.1 on 2023-06-05 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0061_block_fee_reward_block_mev_boost_relay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='orphaned',
            field=models.BooleanField(default=False),
        ),
    ]
