# Generated by Django 4.2.1 on 2023-06-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0062_block_orphaned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='orphaned',
        ),
        migrations.AddField(
            model_name='block',
            name='empty',
            field=models.IntegerField(default=3),
        ),
    ]
