# Generated by Django 4.2.1 on 2023-06-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0063_remove_block_orphaned_block_empty'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='last_mev_reward_fetch_slot',
            field=models.IntegerField(default=0),
        ),
    ]
