# Generated by Django 4.2.1 on 2023-06-07 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0065_alter_missedsync_slot_alter_missedsync_validator_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missedattestation',
            name='slot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='missedattestation',
            name='validator_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='slotblockreward',
            name='epoch',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='slotblockreward',
            name='validator_id',
            field=models.PositiveIntegerField(),
        ),
    ]
