# Generated by Django 4.2.1 on 2023-06-08 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0067_alter_block_epoch'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorbalance',
            name='missed_attestations',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='validatorbalance',
            name='missed_sync',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
