# Generated by Django 4.2.1 on 2023-06-09 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0068_validatorbalance_missed_attestations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='public_key',
            field=models.CharField(max_length=98, unique=True),
        ),
        migrations.AddIndex(
            model_name='validator',
            index=models.Index(fields=['public_key'], name='public_key_idx', opclasses=['text_pattern_ops']),
        ),
    ]
