# Generated by Django 4.2.1 on 2023-06-09 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0069_alter_validator_public_key_validator_public_key_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='validator',
            name='public_key_idx',
        ),
    ]
