# Generated by Django 4.2.1 on 2023-06-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0070_remove_validator_public_key_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='public_key',
            field=models.CharField(db_index=True, max_length=98, unique=True),
        ),
    ]
