# Generated by Django 4.2.1 on 2023-06-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0071_alter_validator_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='epochattestationreward',
            name='validators',
            field=models.ManyToManyField(to='blockfetcher.validator'),
        ),
    ]
