# Generated by Django 4.2.1 on 2023-06-14 10:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0072_epochattestationreward_validators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epochattestationreward',
            name='validator_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None),
        ),
    ]
