# Generated by Django 4.2.1 on 2023-06-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0074_alter_block_block_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='empty',
            field=models.IntegerField(db_index=True, default=3),
        ),
    ]
