# Generated by Django 4.2.1 on 2023-06-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0076_epochreward'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='epochreward',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='epoch',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='validator_id',
            field=models.PositiveIntegerField(db_index=True),
        ),
    ]
