# Generated by Django 4.2.1 on 2023-06-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0077_alter_epochreward_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='average_block_reward',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=27, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='epoch_total_proposed_blocks',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='highest_block_reward',
            field=models.DecimalField(decimal_places=0, default=None, max_digits=27, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='missed_attestation_count',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='participation_percent',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='total_attestations',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
