# Generated by Django 4.2.1 on 2023-06-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0078_epoch_average_block_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
