# Generated by Django 4.2.1 on 2023-06-21 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0079_epoch_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoch',
            name='epoch',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
