# Generated by Django 4.2.1 on 2023-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0080_alter_epoch_epoch'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='validatorbalance',
            index_together=set(),
        ),
        migrations.AlterField(
            model_name='validatorbalance',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='validatorbalance',
            name='missed_attestations',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='validatorbalance',
            name='missed_sync',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='validatorbalance',
            name='slot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='validatorbalance',
            name='validator_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
