# Generated by Django 4.2.1 on 2023-06-23 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0081_alter_validatorbalance_index_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='active_validators',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='exited_validators',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='epoch',
            name='pending_validators',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
