# Generated by Django 4.2.1 on 2023-06-23 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0083_epoch_exiting_statuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='epoch',
            old_name='exiting_statuses',
            new_name='exiting_validators',
        ),
    ]
