# Generated by Django 4.2.1 on 2023-06-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0084_rename_exiting_statuses_epoch_exiting_validators'),
    ]

    operations = [
        migrations.AddField(
            model_name='epoch',
            name='validators_status_json',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
