# Generated by Django 4.2.1 on 2023-06-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0085_epoch_validators_status_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='validator',
            name='withdrawal_type',
            field=models.IntegerField(default=0),
        ),
    ]
