# Generated by Django 4.2.1 on 2023-06-29 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0086_validator_withdrawal_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='last_staking_deposits_update_block',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StakingDeposit',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('block_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=0, default=0, max_digits=27)),
                ('public_key', models.CharField(db_index=True, max_length=98)),
                ('withdrawal_credentials', models.CharField(max_length=66)),
                ('signature', models.CharField(max_length=194)),
                ('transaction_index', models.IntegerField()),
                ('transaction_hash', models.CharField(max_length=66)),
                ('validator', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='blockfetcher.validator')),
            ],
        ),
    ]
