# Generated by Django 4.2.1 on 2023-07-01 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0087_main_last_staking_deposits_update_block_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epoch',
            name='validators_status_json',
            field=models.JSONField(null=True),
        ),
    ]
