# Generated by Django 4.2.1 on 2023-07-01 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0090_remove_attestation_block_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epoch',
            name='id',
        ),
        migrations.AlterField(
            model_name='epoch',
            name='dependent_root',
            field=models.CharField(max_length=68),
        ),
        migrations.AlterField(
            model_name='epoch',
            name='epoch',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
