# Generated by Django 4.2.1 on 2023-07-01 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0091_remove_epoch_id_alter_epoch_dependent_root_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='last_balance_snapshot_date',
        ),
        migrations.RemoveField(
            model_name='main',
            name='last_checked_epoch',
        ),
    ]
