# Generated by Django 4.2.1 on 2023-07-02 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0092_remove_main_last_balance_snapshot_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epochreward',
            name='attestation_head',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='attestation_source',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='attestation_target',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='block_attestations',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='block_attester_slashings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='block_proposer_slashings',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='block_sync_aggregate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='epoch',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='sync_penalty',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='sync_reward',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='epochreward',
            name='validator_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
