# Generated by Django 4.2.1 on 2023-07-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0094_remove_block_attestation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synccommittee',
            name='missed',
        ),
        migrations.RemoveField(
            model_name='withdrawal',
            name='id',
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='index',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
