# Generated by Django 4.2.1 on 2023-07-16 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0094_remove_block_attestation_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synccommittee',
            name='missed',
        ),
    ]
