# Generated by Django 4.2.1 on 2023-07-22 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0096_delete_epochreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorbalance',
            name='total_deposited',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=27),
        ),
    ]
