# Generated by Django 4.2.1 on 2023-07-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0097_validatorbalance_total_deposited'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatorbalance',
            name='status',
            field=models.CharField(choices=[('pending_initialized', 'Pending Initialized'), ('pending_queued', 'Pending Queued'), ('active_ongoing', 'Active Ongoing'), ('active_exiting', 'Active Exiting'), ('active_slashed', 'Active Slashed'), ('exited_unslashed', 'Exited Unslashed'), ('exited_slashed', 'Exited Slashed'), ('withdrawal_possible', 'Withdrawal Possible'), ('withdrawal_done', 'Withdrawal Done'), ('active', 'Active'), ('pending', 'Pending'), ('exited', 'Exited'), ('withdrawal', 'Withdrawal'), ('unknown', 'Unknown')], default='unknown', max_length=19),
        ),
    ]
