# Generated by Django 4.2.1 on 2023-07-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0098_validatorbalance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakingdeposit',
            name='withdrawal_credentials',
            field=models.CharField(db_index=True, max_length=66),
        ),
        migrations.AlterField(
            model_name='validator',
            name='withdrawal_credentials',
            field=models.CharField(db_index=True, max_length=66),
        ),
    ]
