# Generated by Django 4.2.1 on 2023-08-20 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0099_alter_stakingdeposit_withdrawal_credentials_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EthClient',
            fields=[
                ('client_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('repository_owner', models.CharField(max_length=50)),
                ('repo_name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('version', models.CharField(max_length=30)),
                ('release_timestamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
