# Generated by Django 4.2.1 on 2023-08-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0100_ethclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='ethclient',
            name='usage_percentage',
            field=models.FloatField(default=0),
        ),
    ]
