# Generated by Django 4.2.1 on 2023-08-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockfetcher', '0101_ethclient_usage_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='last_missed_attestation_aggregation_epoch',
            field=models.IntegerField(default=-1),
        ),
    ]
